### PR TITLE
Search query params

### PR DESCRIPTION
**Pull request by VortexExpansion**
## Issue
https://github.com/diverta/Kuroco-opendev/issues/5176

## Reviewer
@yabe-diverta 

## Points to be reviewed
- [x] Implement pagination by API in Article page
- [x] Filter by tag area
- [x] Filter by tag keyword
- [x] Filter by search bar  
- [x] Reroute categories into article page.jsx

## Links
https://diverta.gyazo.com/f279c096a3afaa0a8dfe2227955124fe

### CODE REVIEW

**Comment by takel-shiba** [comment]
@yabe-diverta 
レビュー待ち

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Please check bellow.

【General】
- remove `.env` file in PR
- we cannot comment out `output: 'export',` in next.config.js. it's necessary for deploy with KurocoFront

【Home page】
- Looks no implement ranking yet. Please use `/rcms-api/1/ranking` end point. 
https://diverta.gyazo.com/a81e43022e622cd70143d082835210e6

- Sorry, I added `get_favorite_cnt true` setting now. Please show favorite cnt 
https://diverta.gyazo.com/c0dabc79e5d16c8bfbdb86a5740ad323

【Details page】
- Sorry, I added `get_favorite_cnt true` setting now. Please show favorite cnt 
https://diverta.gyazo.com/fb473fe2ac585d25e9110ab9b07b1589

【Article page】
- Please show tag name or keyword which used for filter.
https://diverta.gyazo.com/0582fae2ef9303defc30cbbb907033d2

【Bug】
- When use space in keyword search (ex. `test word`) will error occurs.
https://diverta.gyazo.com/2f2b24b2d21a90c02a2956627873bcc9

**Comment by VortexExpansion** [comment]
@HisashiHasebe , @yabe-diverta san

- [x] .env added to gitignore
- [x] uncommented output:export but had to downgrade the nextJS version to 13.4.19 ([Reference](https://github.com/vercel/next.js/issues/56253#issuecomment-1749058644)) (@yabe-diverta san please check this)
- [x] update ranking in top page https://diverta.gyazo.com/0d3eb5ecb471fe8d89f957d0cc5b37aa
- [x] update fav_cnt in details page https://diverta.gyazo.com/41d36315eff0fa8ec3f80bc14c86cfb1
- [ ] Showing tag name or keyword which is used for filter would be a little complex for me now. Firstly, because for tag display I use the tag_id and the tag_nm is fetched later after display. I will try to change this in a later PR because this would require a lot of code changes now.
- [x] Keyword search with spaces bug fixed https://diverta.gyazo.com/3be6b28c8fd2030dc1a624c246e49026 

Please review and confirm the changes.

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Does the implementation include pagination in this pull request? It is not possible to navigate between pages while maintaining the filters.
https://diverta.gyazo.com/dfe4ecb31e025bc58d02458eee9648d6

**Comment by HisashiHasebe** [comment]
Please update this.
- [x] Update fav_cnt in list page https://diverta.gyazo.com/9619a6b57d50adb26cd7a841d0cd77fa
- [x] Fix broken links https://diverta.gyazo.com/e383a483dde84566b28782dbd9d2d4a3

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 

- [x] fixed pagination https://diverta.gyazo.com/ab7b35dfd1e5d4c8431a2c6db2d8bc98
- [x] updated fav_cnt https://diverta.gyazo.com/115076f164e9c1f6a634c0620b11ffc2
- [x] fixed broken links https://diverta.gyazo.com/49cdc895e1b59a8b59037615f4000897

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Thank you!

And sorry, one more point.
Detail page's header looks difference with mock.
Please check it.

mock:https://diverta.gyazo.com/0d4821eb9dda902e4d63e909d4ede91c
current:https://diverta.gyazo.com/c1a0744bbc113240837e7cafa69726f6

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Top page also.
https://diverta.gyazo.com/fa580474d612bcbb57b03a356f6d0f34

**Comment by VortexExpansion** [comment]
@HisashiHasebe san

Details page is fixed https://diverta.gyazo.com/7d7ca0a7182e203bb4cd5dea2ddf3bad

I created a new PR for implementing the Top page header animation because that required a change in folder architecture and could have broken other things. https://github.com/diverta/front_next_media/pull/5

**Pull request merged**
