### PR TITLE
contact page

### LINKED ISSUE #17: Implement contact page
https://dev-next-media.g.kuroco-front.app/mock/contact/index.html

### PR DESCRIPTION
**Pull request by VortexExpansion**
Fixes #17 

Fully added functionality of contact page

### CODE REVIEW

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 

This PR is ready for review. Please test locally 🙇 

I also fixed most part of the kuroco backend for this 
https://dev-next-media.g.kuroco-mng.app/management/inquiry/inquiry_disp_edit/?inquiry_id=1
Please check if anything else also needs change

Two things to note 
- [ ] File upload logic is working correctly but is not passed to the request because `JSON.stringify` is used later which prevents file upload conversion I think. So file upload will not work now
- [x] Matrix (multiple choice) shows weird behaviour for 3rd column but works fine for the other 2 columns. Minor bug, would investigate it later

I would also get these points reviewed by @yabe-diverta san later if necessary

If these are minor issues since this is only a template site and everything else seems fine to you, please review and merge.

**Comment by VortexExpansion** [comment]
Also @HisashiHasebe san

I found a very minor enhancement while preparing the backend for inquiry list which I think can be raised as an issue in opendev repo.
https://dev-next-media.g.kuroco-mng.app/management/inquiry/inquiry_disp_edit/?inquiry_id=1

The button is labelled `settings` instead of `update`, a bit misleading. Very minor I think, can fix it easily.
Thought I'll let you know. 
Link : https://diverta.gyazo.com/e625d7b0dd33821753d2d740d7034638

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
I will check locally soon.
But I think file upload is needed. It's very important field.

> The button is labelled settings instead of update, a bit misleading. Very minor I think, can fix it easily.
Thought I'll let you know.

I think It's OK, Because the change will not reflect until you press the Update button here.
https://diverta.gyazo.com/48fec911b18fed9afdb2bededa5229f2

If settings label make you confuse, Close button is better. I think.

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
In addition to the two existing ones, please update the following.
We would like to have basically the same functionality as the corporate sample site.

- [ ] Retrieve required settings from the Kuroco admin panel
- [ ] Retrieve field title and options from the Kuroco admin panel

**Comment by VortexExpansion** [comment]
Please verify the following points now @HisashiHasebe san 

- [x] Retrieve required settings from the Kuroco admin panel
- [x] Retrieve field title and options from the Kuroco admin panel
- [x] Matrix multiple choice behaviour fixed
- [x] Please review the implementation of datepicker. I changed it from sample hardcoded values like 1,2,3,....31 to run a loop. Please let me know if this is OK 
- [x] File upload fixed 
- [x] Sample code commented out in this PR for form builder in case anything fails. Will delete this commented code after you verify the working of retrieved form builder then you can merge

**Comment by VortexExpansion** [comment]
@HisashiHasebe san 
File upload is also fixed ✨ 

You can review now. If this seems ready for merge after your testing, let me know, I will delete the commented sample code and then you can merge 🙇

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
1. body does not work as an optional field.(maybe name and email has same issue)
https://diverta.gyazo.com/def03f02e531745b0fd072427770d910
2. If either name, email, or body is not filled in, the required setting error is not displayed.
https://diverta.gyazo.com/2776c0c1fe6f686295da907e29f3c444

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Sorry, one more thing.
Please use [Description ](https://diverta.gyazo.com/626d95709de8d1039ba92b101a9bf81a) to this word
https://github.com/diverta/front_next_media/blob/d33414af6247c7fe1decb10b3e08d38de04a3d02/src/app/(pages)/(SigleColumn)/contact/page.jsx#L208-L217

**Comment by VortexExpansion** [comment]
Fixed ✨ 

Please review again @HisashiHasebe san

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Thank you! Looks good for me.
Please delete the commented sample code.

**Comment by VortexExpansion** [comment]
@HisashiHasebe 

Ready for merge

**Pull request merged**
