### PR TITLE
fix sitemap

### LINKED ISSUE #41: feature list in sitemap.xml
@HisashiHasebe san 

Sitemap.xml has the wrong implementation for feature list currently. I will fix that. 
https://diverta.gyazo.com/d11d4da8cafafc621e1fa9fbb99c9b60

At the same time, there is no API for fetching information of all the featured stories. The only API is `/rcms-api/1/pickup/list` which has the condition of `cnt=2` for display. 

Suggestion : add a new API `/rcms-api/1/pickup/all` which recursively fetches all featured stories with pagination and perPage limit of `200` similar to the new behaviour of `/rcms-api/1/content/all` #40

### PR DESCRIPTION
**Pull request by VortexExpansion**
Fixes #41

### CODE REVIEW

**Comment by VortexExpansion** [comment]
@yabe-diverta @HisashiHasebe 
Please review.

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Is it correct to include all pickup contents in the sitemap?
Currently, 3 Feature Stories are registered, but topics_id=17 (https://dev-next-media.g.kuroco-front.app/feature/17/) has not been generated.
Shouldn't the sitemap also only include the two pickup contents?

**Comment by VortexExpansion** [comment]
@HisashiHasebe @yabe-diverta 

I understood your point now. 
Since the website will only feature the latest top 2 featured articles, it's better to include only those top 2 articles in the sitemap. 

My initial logic was to keep all possible content in the sitemap but since it cannot be accessed from anywhere else there is no point in storing past featured articles. 

Will reflect the change accordingly.

**Comment by VortexExpansion** [comment]
@HisashiHasebe @yabe-diverta 

Ready for review and merge ✨

**Comment by HisashiHasebe** [comment]
@VortexExpansion 
Looks good for me.

generated sitemap.xml is good.
https://diverta.gyazo.com/6b69c6778625ca285bf8b151512f4028

**Review by HisashiHasebe — APPROVED** [review]

**Review by yabe-diverta — APPROVED** [review]

**Pull request merged**
