### PR TITLE
mobile Navbar fixes

### LINKED ISSUE #38: Menu does not close after page transition
@VortexExpansion
CC) @HisashiHasebe 

Menu does not close after page transition when viewed on a mobile phone.
https://diverta.gyazo.com/aa6a60e45fb04b19fc4260e2c093810c

### PR DESCRIPTION
**Pull request by VortexExpansion**
Fixes #38 

## Reviewer
@mimori @HisashiHasebe 

## Link 
https://diverta.gyazo.com/d90e926be5e43ef348a69c2e1a453c20

## Changes 
- [x] fixed toggle for mobile view
- [x] fixed register page reroute
- [x] fixed logout button

### CODE REVIEW

**Comment by VortexExpansion** [comment]
@mimori @HisashiHasebe 
Please review and confirm.

**Comment by mimori** [comment]
@VortexExpansion @yabe-diverta 
I got an error in GithubActions after merging, can you fix it?
GithubActionsでエラーになってしまったのですがわかりますか？？

https://github.com/diverta/front_next_media/actions/runs/9283787130/job/25544709943

**Comment by VortexExpansion** [comment]
@mimori san
I manually run `main` build again
https://github.com/diverta/front_next_media/actions/runs/9284768187

Seems to work fine now. Not an issue maybe ?

**Comment by mimori** [comment]
@VortexExpansion 
Thanks, that looks fine.
And I checked your fix.

**Pull request merged**
