### PR TITLE
add metadata for client components

### LINKED ISSUE #33: Metadata for client components
Based on comment https://github.com/diverta/front_next_media/pull/32#issuecomment-2115351713

### PR DESCRIPTION
**Pull request by VortexExpansion**
Fixes #33 

## Reviewer 
@yabe-diverta san 

## Checklist 
- [x] Login https://diverta.gyazo.com/d6d2af3f7aba12b092043542869d38c6
- [x] Contact https://diverta.gyazo.com/739c878fe2d5a4822bc3bc1256b8ca33
- [x] Register https://diverta.gyazo.com/8a7ae43b3c39ec1e7a33980cd2d830b4
- [x] Register/Reminder https://diverta.gyazo.com/67c173c2bddafef7a38592fe6b37347f
- [x] Member pages (My page/Edit/Delete) https://diverta.gyazo.com/6454694ce7878bcd5cf8906b9d077221
- [x] Limited content https://diverta.gyazo.com/4b2580be726b2f02a8d38c85e9d07cdb

### CODE REVIEW

**Review by yabe-diverta — APPROVED** [review]
@VortexExpansion 
No other screens?
only Login page?

**Comment by VortexExpansion** [comment]
@yabe-diverta 
Wanted to confirm if this is the right way. 
Will do the same for the remaining client components

**Comment by yabe-diverta** [comment]
@VortexExpansion 
I see~~~ yes I think there is no issues in your PR.

**Comment by VortexExpansion** [comment]
@yabe-diverta san 
Updated for the remaining pages too. 

Ready for review/merge.

**Review by yabe-diverta — APPROVED** [review]
No issues 🙇

**Comment by VortexExpansion** [comment]
@HisashiHasebe  san
Please confirm and merge.

**Pull request merged**
